eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8091
spring:
  application:
    name: EmailSender-microservice
  mail:
    host: smtp.gmail.com
    port: 587
    username: jaidanemohammed@gmail.com
    password: ykty vodj nifa xrtv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

