eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
server:
  port: 8091
spring:
  application:
    name: EmailSender-microservice
  cloud:
    service:
      service-registry:
        auto-registration:
          fail-fast: true
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/eside-notification?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: jaidanemohammed@gmail.com
    password: ykty vodj nifa xrtv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

