eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://localhost:8090
          predicates:
            - Path= /api/v1/auth/**
        - id: account
          uri: http://localhost:8093
          predicates:
            - Path= /api/account/** , /api/feedBack/** , /api/information/** , /api/favorite/**
        - id: advertisment
          uri: http://localhost:8095
          predicates:
            - Path= /api/advertisement/** , /api/image/** , /api/product/** , /api/subcategories/** , /api/categories/**
        - id: emailSender
          uri: http://localhost:8091
          predicates:
            - Path= /api/v1/mail/**
        - id: order
          uri: http://localhost:8097
          predicates:
            - Path= /api/discount-request/** , /api/order/**
        - id: payment
          uri: http://localhost:8094
          predicates:
            - Path= /api/bank-data/** , /api/transactions/** , /api/wallet/** , /api/payment/**
  application:
    name: gateway
