spring:
  profiles:
    active: prod
  application:
    name: gateway
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20

logging.level:
  org.springframework.retry: trace
  com.netflix.discovery: trace
