
logging.level:
  org.springframework.retry: trace
  com.netflix.discovery: trace

#Variables
feign:
  client:
    advertisment:
      url: gateway-application:8222/api/account
    image:
      url: gateway-application:8222/api/image
    payment:
      url: gateway-application:8222/api/wallet