spring:
  profiles:
    active: dev
  application:
    name: order-microservice
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20

logging.level:
  org.springframework.retry: trace
  com.netflix.discovery: trace