name: Eside Backend Pipeline

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - account/**
      - advertisment/**
      - auth/**
      - config-server/**
      - discovery/**
      - EmailSender/**
      - gateway/**
      - Order/**
      - payment/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

env:
  MODULES: "EmailSender/EmailSender Order/Order account/account advertisment/advertisment auth/auth config-server/config-server discovery/discovery gateway/gateway payment/payment"

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Compile projects
        run: |
          for module in ${{ env.MODULES }}; do
            echo "---------- $module ----------"
            cd $module
            echo "Compiling the code..."
            mvn compile
            echo "Compile complete."
            cd - > /dev/null
          done

  build:
    runs-on: ubuntu-latest
    name: Build Backend
    needs: [compile]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        run: |
          for module in ${{ env.MODULES }}; do
            echo "---------- $module ----------"
            cd $module
            echo "Building the code..."
            mvn package -DskipTests
            echo "Build complete."
            cd - > /dev/null
          done

  build-image:
    runs-on: ubuntu-latest
    needs: [build]
    name: Build Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Login to DOCKER_HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & push Docker images
        run: |
          for module in ${{ env.MODULES }}; do
            echo "---------- $module ----------"
            cd $module
            echo "Building Docker image..."
            module_name=$(basename $module | tr '[:upper:]' '[:lower:]')
            docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest .
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest
            echo "Docker image for $module pushed to Docker Hub."
            cd - > /dev/null
          done

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-image ]
    name: Deploy Backend
    steps:
      - name: create deployment folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            mkdir -p ci-cd

      - name: Copy docker-compose file to VPS
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          local: 'docker-compose.yml'
          remote: '.'
